apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: site
spec:
  replicas: 2
  selector:
    matchLabels:
      app: site
  template:
    metadata:
      labels:
        app: site
    spec:
      containers:
      - name: docker-container
        image: zemts/project:1.0.0
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /index.html
            port: 8000
          initialDelaySeconds: 4
          periodSeconds: 4
        livenessProbe:
          httpGet:
            path: /index.html
            port: 8000
          initialDelaySeconds: 8
          periodSeconds: 8